# kubearmor-dev_test_09

apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: hsp-kubearmor-dev-file-dir-block-fromsource
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: kubearmor-dev
  severity: 5
  file:
    matchDirectories:
    - dir: /etc/cron.d/
      fromSource:
      - path: /usr/bin/head
  action:
    Block

# test

# $ head /etc/cron.d/mdadm
# cat: mdadm: Permission denied
# $ head /etc/hostname
# kubearmor-dev

# expectation
# /usr/bin/head cannot access /etc/cron.d/*
# /usr/bin/head can access any others
