name: ci-test-systemd

on:
  push:
    branches: [main]
    paths:
      - "KubeArmor/**"
      - "tests/**"
      - "protobuf/**"
      - ".github/workflows/ci-test-systemd.yml"
  pull_request:
    branches: [main]
    paths:
      - "KubeArmor/**"
      - "tests/**"
      - "protobuf/**"
      - ".github/workflows/ci-test-systemd.yml"

jobs:
  build:
    name: Test KubeArmor in Systemd Mode
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-18.04]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/setup-go@v3
        with:
          go-version: v1.18

      - name: Install the latest LLVM toolchain
        run: |
          . /etc/os-release

          sudo apt-get -y install build-essential libelf-dev pkg-config
          wget https://apt.llvm.org/llvm.sh -O /tmp/llvm.sh

          if [ "$VERSION_CODENAME" == "focal" ] || [ "$VERSION_CODENAME" == "bionic" ]; then
            sudo bash /tmp/llvm.sh 12
            for tool in "clang" "llc" "llvm-strip"; do
              sudo rm -f /usr/bin/$tool
              sudo ln -s /usr/bin/$tool-12 /usr/bin/$tool
            done
          else # VERSION_CODENAME == jammy
            sudo bash /tmp/llvm.sh 14
            for tool in "clang" "llc" "llvm-strip"; do
              sudo rm -f /usr/bin/$tool
              sudo ln -s /usr/bin/$tool-14 /usr/bin/$tool
            done
          fi

      - name: Compile libbpf
        run: |
          cd KubeArmor/BPF
          make -C libbpf/src

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          install-only: true

      - name: Build Systemd Release
        run:  make local-release
        working-directory: KubeArmor

      - name: Install KubeArmor
        run:  sudo apt install -y ./dist/kubearmor*.deb
        working-directory: KubeArmor

      - name: Check journalctl
        run: sudo journalctl -u kubearmor --no-pager
