name: systemd-release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/setup-go@v3
        with:
          go-version: v1.18

      - name: Install the latest LLVM toolchain
        run: |
          . /etc/os-release

          sudo apt-get -y install build-essential libelf-dev pkg-config
          wget https://apt.llvm.org/llvm.sh -O /tmp/llvm.sh

          if [ "$VERSION_CODENAME" == "focal" ] || [ "$VERSION_CODENAME" == "bionic" ]; then
            sudo bash /tmp/llvm.sh 12
            for tool in "clang" "llc" "llvm-strip"; do
              sudo rm -f /usr/bin/$tool
              sudo ln -s /usr/bin/$tool-12 /usr/bin/$tool
            done
          else # VERSION_CODENAME == jammy
            sudo bash /tmp/llvm.sh 14
            for tool in "clang" "llc" "llvm-strip"; do
              sudo rm -f /usr/bin/$tool
              sudo ln -s /usr/bin/$tool-14 /usr/bin/$tool
            done
          fi

      - name: Compile libbpf
        run: |
          cd KubeArmor/BPF
          make -C libbpf/src

      - name: Install karmor
        run: curl -sfL https://raw.githubusercontent.com/kubearmor/kubearmor-client/main/install.sh | sudo sh -s -- -b .
        working-directory: KubeArmor

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
          workdir: KubeArmor
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
